// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvplsldnjervklcrrxrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cGxzbGRuamVydmtsY3JyeHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDk1NDEsImV4cCI6MjA2MjI4NTU0MX0.-MUPtE9h51DNKS4ab6tMNNqqH4PLJBF6bn21BEBdZN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);